global:
   enabled: true
   tlsDisable: false
injector:
   enabled: true
server:
   extraEnvironmentVars:
      VAULT_CACERT: /ca/ca-homelab.crt
   volumes:
      - name: ca-homelab-volume
        secret:
         defaultMode: 420
         secretName: ca-homelab-secret
   volumeMounts:
      - mountPath: /ca
        name: ca-homelab-volume
        readOnly: true
   standalone:
      enabled: false

configs:
  cm:
    accounts.readonly: apiKey
  rbac:
    policy.csv: "g, readonly, role:readonly"
