FROM nginx:alpine

RUN rm /usr/share/nginx/html/index.html

COPY role/docker/files/docker_images/khaddict.com/index.html /usr/share/nginx/html/

COPY role/docker/files/docker_images/khaddict.com/pepe_cool.png /usr/share/nginx/html/

EXPOSE 80
