route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: prometheus_alerts_discord

receivers:
- name: prometheus_alerts_discord
  discord_configs:
  - webhook_url: '{{ webhook_url }}'
