global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9093'

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets:
          {% for host in hosts -%}
          - '{% if host == "stackstorm.homelab.lan" %}{{ host }}:9200{% else %}{{ host }}:9100{% endif %}'{% if not loop.last %}
          {% endif -%}
          {% endfor %}
    relabel_configs:
      - source_labels: [__address__]
        regex: '^([^:]+):[0-9]+$'
        replacement: '$1'
        target_label: instance

  - job_name: 'blackbox_icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 5s
    static_configs:
      - targets:
          {% for host in hosts -%}
          - '{{ host }}'{% if not loop.last %}
          {% endif -%}
          {% endfor %}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.homelab.lan:9115

  - job_name: elasticsearch
    metrics_path: /metrics
    params:
      target:
        - 'elk.homelab.lan'
    static_configs:
      - targets:
          - 'elk.homelab.lan:9114'
    relabel_configs:
    - source_labels: [__address__]
      regex: '^([^:]+):[0-9]+$'
      replacement: '$1'
      target_label: instance
