apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: khaddict.com
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: khaddict
    server: https://kubernetes.default.svc
  source:
    path: role/kcli/files/khaddict.com/helm_chart
    repoURL: https://github.com/khaddict/homelab.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
