apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: khaddict
  namespace: khaddict
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`khaddict.homelab.lan`)
      services:
        - name: khaddict
          port: 80
  tls:
    secretName: khaddict-cert-secret
