apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homepage
    server: https://kubernetes.default.svc
  source:
    path: role/kcli/files/homepage/helm_chart
    repoURL: https://github.com/khaddict/homelab.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
